backend:
  name: git-gateway
  branch: main

media_folder: "assets/img/galerie"
public_folder: "/assets/img/galerie"

collections:
  - name: "galerie"
    label: "Galerie photos"
    folder: "content/galerie"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text", required: false }
